# Site settings
title: ohaut - Opensource Home Automation
email: miguelangel@ajo.es
description: "Opensource Home AUTomation"
baseurl: ""
url: "https://ohaut.github.io"

# Build settings
markdown: kramdown
permalink: pretty
